// layout.js - this file is the main layout that will be applied to ALL rendered pages.
// It imports the AppProvider component which is wrapped around the component tree, {children}, and
// makes the store's state available from any component in the app.

import './globals.css'
import './components/cards/cards.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import AppProvider from './appProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Flashcards',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-gray-50'>
      <body className={inter.className}>
        <nav className='text-xl flex flex-row justify-center gap-5 bg-purple-600 text-purple-200 font-bold p-3'>
          <Link href={"/"} className='hover:text-purple-50 transition ease-in duration-300'>Home</Link>
          <Link href={"/topics"} className='hover:text-purple-50 transition ease-in duration-300'>Topics</Link>
          <Link href={"/quizzes"} className='hover:text-purple-50 transition ease-in duration-300'>Quizzes</Link>
          <Link href={"/new-quiz"} className='hover:text-purple-50 transition ease-in duration-300'>New Quiz</Link>
        </nav>
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  )
}
